### PR TITLE
Fix page anchors for entries with apostrophes

### PR DESCRIPTION
**Pull request by featherbear**

### CODE REVIEW

**Comment by garethtdavies** [comment]
Thanks for the contribution @featherbear. Can you just add a footer to your commit with the following for the CI to pass:

```
Change-type: patch
```

If you can amend the commit to add that and push it back up, the tests should succeed (more info in CONTRIBUTING.md see https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md).

@chrisys I remember you mentioning something about broken anchors see https://github.com/balena-io/doxx/commit/dc030315f34dafea6b966c97d6b1d82ab90d9358. I've tested this fix locally but anything else to be aware of? I'm guessing these links reference the old way the links were being generated?

**Comment by featherbear** [comment]
@garethtdavies Ahh I had forgotten to take a look at the contributors document! Oops!

I've added the footer as requested

**Comment by xginn8** [comment]
@balena-ci retest

**Comment by garethtdavies** [comment]
@balena-ci retest

**Pull request merged**
