### PR TITLE
patch: Update local mode

### PR DESCRIPTION
**Pull request by mpous**
Updated Local Mode page.

Signed-off-by: Marc Pous (@mpous) [marc@balena.io](mailto:marc@balena.io)

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Hello @mpous why don't you try giving the prefix method a try, which I mentioned to you before. Here the error is that I think `change-type` needs to have a C capital like `Change-type`

You seem to have missed the commit prefix to signify the change-type for your PR. Please read https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md#creating-commits-in-line-with-semantic-versioning 
Try adding a commit with a prefix as mentioned here ^

**Comment by vipulgupta2048** [comment]
Hey @mpous, There needs to be a line break before the Change-type message because it needs to be in the footer of the commit message. That's what's going wrong. But, it would help if you weren't writing change-type messages this way anyway. 

I am repeatedly pointing out the Contributing guide in my messages because this way of writing `Change-type` message in the footer of the commit leads to many errors. It has to be done in a certain way because that's what versionbot understands. Instead of committing like this, how about trying to add a prefix to your `Update local-mode.md` message and make it like `patch: Update local-mode.md`. This should be enough. 

I hope this is helpful. Are there any blockers to using the change-type as a prefix to the commit heading or do let me know if the contributing guide is not clear enough for what needs to be done? Please do give it a shot, don't worry about the number of commits. I can squash that.

**Comment by vipulgupta2048** [comment]
Thanks for making the required changes, any reason you chose to make the PR on a fork of this repo?

**Comment by mpous** [comment]
@vipulgupta2048 I'm currently doing PRs to other docs where I need to fork on my repo and PR. And this is how i proceeded. Is this ok?

**Comment by vipulgupta2048** [comment]
Closed in favor of #2464

**Pull request closed without merging**
