### PR TITLE
patch: Updating screencaps in Account Management

### PR DESCRIPTION
**Pull request by mpous**
Updated screencaps from the Access Tokens in Account Management.

Need to check the widths of the screencaps once on production with different browsers.

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@mpous I have deployed your branch to staging. This way you can check your changes before they hit prod.

**Comment by vipulgupta2048** [comment]
LGTM, merge this PR by issuing the `I self-certify!` command to approve the PR. 
Reference: https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md#balenistas-only-using-versionbot-to-manage-your-pull-request

**Comment by mpous** [comment]
@balena-ci I self-certify!

**Comment by vipulgupta2048** [comment]
@mpous To get your branch updated with the master branch, one should rebase using versionbot. Having a merge commit when you update your branch using the GitHub UI often adds up to noise in the history and may have an undesirable effect. You can instead make use of Versionbot to rebase your branch. Check out the command `@balena-ci rebase` https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md#balenistas-only-using-versionbot-to-manage-your-pull-request

Though it doesn't work when someone has already used the Github UI to update the PR.

**Pull request merged**
