### PR TITLE
Remove unsupported GPIO file system access method

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Additionally removed commented section on GPIO pins

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Review by acostach — APPROVED** [review]
lgtm

**Review by myarmolinsky — APPROVED** [review]

**Comment by lurch** [comment]
For future reference, the Balena folks may find "A history of GPIO usage on Raspberry Pi devices, and current best practices" at https://pip.raspberrypi.com/categories/685-whitepapers-app-notes-compliance-guides a useful resource.

**Comment by lurch** [comment]
BTW I see that this page also says "We recommend [Pi Pins][pi-pins] for node.js projects" but according to https://www.npmjs.com/package/pi-pins it was last published 11 years ago (!) and it also uses sysfs, so it'll stop working on newer Linux kernels.

**Comment by vipulgupta2048** [comment]
@lurch What's the current recommendation for Node.js projects from Raspberry Pi

**Comment by lurch** [comment]
@vipulgupta2048 I've got no idea; I don't think that Node.js is something that any of the Raspberry Pi Engineers have looked at.
A quick look at https://www.google.com/search?q=nodejs+libgpiod finds https://www.npmjs.com/package/node-libgpiod which looks like it _might_ do the job, but I've not tried it myself and obviously it's up to Balena to do any testing.

**Comment by ghollingworth** [comment]
Yeah something based on libgpiod would be best supported, as long as it’s the correct version (shame that they didn’t get the api right the first time!)

**Pull request merged**
