### PR TITLE
patch: add new ESR devices

### PR DESCRIPTION
**Pull request by shawaj**
Add new ESR devices

Change-type: patch
Signed-off-by: Aaron Shaw <shawaj@gmail.com>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by klutchell** [comment]
@balena-ci retest

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
Looks good to me @shawaj, can you rebase and I'll approve?

**Comment by vipulgupta2048** [comment]
@shawaj can you please rebase the PR and we can get these added?

**Comment by shawaj** [comment]
Sorry missed this. One sec

**Comment by shawaj** [comment]
All done @klutchell @vipulgupta2048

**Review by klutchell — APPROVED** [review]

**Comment by klutchell** [comment]
Thanks again for your contributions @shawaj !

**Pull request merged**
