### PR TITLE
Drop old no longer used network configuration images

### PR DESCRIPTION
**Pull request by thgreasi**
Change-type: patch
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Review by vipulgupta2048 — COMMENTED** [review]
Thanks for making the PR. You the real MVP @thgreasi I can't actually verify what is being deleted but I trust you ❤️ 😂  Ship it when you feel like it.

**Comment by thgreasi** [comment]
@balena-ci rebase

**Comment by thgreasi** [comment]
Indeed @vipulgupta2048 I also faced that issue :)
I could only find them in the GH repo by copying the name and using "Go to file" on master...

**Comment by thgreasi** [comment]
@balena-ci I self-certify!

**Comment by lurch** [comment]
This is where using a local clone of the repo and the git cli comes in handy :wink: 
```bash
$ git grep 'network.*\.png'
pages/learn/getting-started.md:<img alt="Network configuration" src="/img/common/app/network.png" width="80%">
```

**Comment by thgreasi** [comment]
Hey @lurch :wave: :)
Didn't `git grep` (TIL that's a thing), just searched using my IDE.

**Pull request merged**
