### PR TITLE
Updated Device Type Listings

### PR DESCRIPTION
**Pull request by rhampt**
Update the tables showing device-types to direct user to balenaHub

Change-type: patch
Signed-off-by: Ryan Hampton (@rhampt) <rhampt@balena.io>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Review by vipulgupta2048 — COMMENTED** [review]
This page https://www.balena.io/docs/reference/base-images/devicetypes/ doesn't hold complete parity with information on Hub. Is there a plan for base images to be also listed on Hub?

If not, then I recommend not redirecting customers to the Hub page just yet

**Comment by vipulgupta2048** [comment]
I also updated the PR to delete the JS logic bit that you missed. Let me know if the base images bit is happening. We need to do the same for that too.

**Comment by rhampt** [comment]
@vipulgupta2048

> This page https://www.balena.io/docs/reference/base-images/devicetypes/ doesn't hold complete parity with information on Hub. Is there a plan for base images to be also listed on Hub? 

Correct it is currently missing the Repo links, which are presumably should be an easy addition to the hub. I captured this, along with including the latest balenaOS release for each type in this issue in the hub repo: https://github.com/balena-io/balenahub/issues/391

> If not, then I recommend not redirecting customers to the Hub page just yet

I respectfully disagree. Reasoning: I don't think those links aren't used much as the pages themselves are rarely visited. So, if I'm wrong and a customer needed them they could reach out to CS/Support in the days/weeks between now and the issue being picked up on hub. Including the repo link on hub is a quick, easy, & controversial win—I don't think it will take long to get addressed, and a gap is fine. Let's get a third party to weigh in. @rahul-thakoor maybe? Anyone else with strong opinions?

> I also updated the PR to delete the JS logic bit that you missed. Let me know if the base images bit is happening. We need to do the same for that too.

Thanks, I totally missed deleting those files! What do you mean by the "base images bit"?

**Comment by rahul-thakoor** [comment]
yeah, I'm not sure we need to block on the base images link

I think the base images repo is already linked https://www.balena.io/docs/reference/base-images/base-images/

we can perhaps add a short description (if needed) on how they are generated

**Comment by vipulgupta2048** [comment]
I am fine as well. You can go ahead and make the changes @rhampt

**Comment by rhampt** [comment]
@balena-ci I self-certify!

**Comment by vipulgupta2048** [comment]
Ryan, what I meant by the “balena Images” bit was that you need to delete
HTML partials for the balena images and architecture page as well. That’s
what I meant with going ahead and making the changes. --
Best,
Vipul Gupta
@vipulgupta2048 <https://twitter.com/vipulgupta2048> | Mixster
<https://mixstersite.wordpress.com>

**Comment by rhampt** [comment]
Ah, okay gotcha @vipulgupta2048 . I assumed "base images" had to do with the docker base image repo links that were included in one of the tables and should be brought over to hub.

**Comment by vipulgupta2048** [comment]
@rhampt Will you be making the required changes or should I open a new PR?

**Comment by rhampt** [comment]
@vipulgupta2048 I'd appreciate if you opened another PR. I'm not super clear on the docs structure just yet in regards to those HTML partials. I hope to learn from you what I missed when removing the tables!

**Comment by vipulgupta2048** [comment]
Done

**Pull request merged**
