### PR TITLE
Removed Supervisor Upgrade Policy link

### PR DESCRIPTION
**Pull request by rmorillo24**
Change-type: patch
Signed-off-by: Rafael Morillo <rafael@balena.io>

### CODE REVIEW

**Review by pdcastro — APPROVED** [review]
I've noticed that this PR is not linked to any issue. Mentioning this just in case an issue exists.

**Review by 20k-ultra — CHANGES_REQUESTED** [review]
I (Miguel) said we can remove this but @xginn8 thinks we should leave it so more discussion is needed.

**Comment by cmfcruz** [comment]
@balena-ci rebase

**Comment by cmfcruz** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@20k-ultra Should we close this PR or what should we do?

**Comment by 20k-ultra** [comment]
@vipulgupta2048 I'm going to make a PR where this upgrade policy remains but it will be in this repository rather then the Supervisor so no need to download and I think upgrade policy is not something the Supervisor repository cares about. It's just saying we can do it if there's a bug.

**Pull request closed without merging**
