### PR TITLE
docs: Update 'Reduce bandwidth usage' page with clarifications

### PR DESCRIPTION
**Pull request by maggie0002**
Added column to Data Usage table to clarify which variable are associated with each data use. 

Change-type: patch
Signed-off-by:

### CODE REVIEW

**Comment by chrisys** [comment]
@maggie0002 thanks for the contribution!

Please see the [contributing guidelines](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) for instructions on how to format your commit message correctly for this repo.

**Review by vipulgupta2048 — COMMENTED** [review]
@maggie0002 thanks for the contribution! Can you make changes to your PR as per Chris's suggestion.

**Comment by maggie0002** [comment]
Will do, sorry, seem to have missed Chris's comment. Currently having internet issues but will be sure to make the amendment as soon as possible,

**Comment by maggie0002** [comment]
> @maggie0002 thanks for the contribution! Can you make changes to your PR as per Chris's suggestion.

Hopefully ok now.

**Comment by 20k-ultra** [comment]
@maggie0002 I'll confirm the bytes/second haven't change on Monday but in the meantime, can you update the PR to use `BALENA_` rather then `RESIN_`. Both work however, we want to work on eventually having only Balena mentioned in the docs to avoid confusion in the future :p

**Comment by vipulgupta2048** [comment]
@20k-ultra I actually forced pushed the commits in the right format to make the CI happy, do let us know if the bytes/second are fine and I can get the variables sorted then :+1:

**Comment by maggie0002** [comment]
> @maggie0002 I'll confirm the bytes/second haven't change on Monday but in the meantime, can you update the PR to use `BALENA_` rather then `RESIN_`. Both work however, we want to work on eventually having only Balena mentioned in the docs to avoid confusion in the future :p

Change RESIN_ to BALENA_

**Comment by vipulgupta2048** [comment]
@20k-ultra Got a update for us.

**Comment by 20k-ultra** [comment]
@vipulgupta2048 I don't have the bandwidth atm to confirm the network usage is correct but that is out of the scope for this PR anyways since this PR isn't changing them.

@maggie0002 thanks for making the change I mentioned!

LGTM but the tests are failing with:

```
Step 5/10 : RUN npm install

 ---> Running in f31954444bd9

npm WARN EBADENGINE Unsupported engine {

npm WARN EBADENGINE   package: 'resin-docs@5.2.2',

npm WARN EBADENGINE   required: { node: '^10.0.0' },

npm WARN EBADENGINE   current: { node: 'v15.5.1', npm: '7.3.0' }

npm WARN EBADENGINE }
```

Vipul are you able to help figure that out ?

**Comment by vipulgupta2048** [comment]
@20k-ultra Sure thing, this test always seem to fail in other PR's that I have seen as well. I will see if I can fix it with a quick PR to update the engine in package.json otherwise I will take care of this. Thanks for the assist! :cookie:

**Comment by vipulgupta2048** [comment]
@balena-ci retest

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Review by vipulgupta2048 — APPROVED** [review]
LGTM

**Pull request merged**
