### PR TITLE
Adding genericX86_64 to the device types to try

### PR DESCRIPTION
**Pull request by rmorillo24**
Change-type: patch
Signed-off-by: Rafael Morillo <rafael@balena.io>

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Review by pdcastro — APPROVED** [review]
This PR does not seem to be linked to any issue. Mentioning this just case an issue exists.

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Pull request merged**
