### PR TITLE
Drop unused properties from device.json

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Namely, insturctions, machine and state were properties aren't being used anywhere
in the documentation and hence were removed.

Change-type: patch
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@balena-ci retest

**Comment by klutchell** [comment]
Aren't we using the device instructions property here?
https://github.com/balena-io/docs/blob/master/shared/getting-started/getDeviceOnDash/_default.md

**Comment by vipulgupta2048** [comment]
Good find @klutchell I wasn't able to find any instances of `device.instructions` when I searched for it. You are infact correct, the instructions are getting used here for only those files whose partials are not here: https://github.com/balena-io/docs/tree/master/shared/getting-started/getDeviceOnDash

For example this device, https://www.balena.io/docs/learn/getting-started/nitrogen8mm-dwe/nodejs/#provision-device

**Comment by vipulgupta2048** [comment]
I can bring back the instructions for devices that don't have partials to avoid duplication of content.

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
Check it out @klutchell

**Comment by lurch** [comment]
Just out of curiosity I decided to do a bit of "digital archaeology" :wink: and it looks like the `community` flag was added in #1391 but then obsoleted in #1580

**Comment by klutchell** [comment]
@mehalter I got the impression from our last arch brainstorm that all of this information is migrating to a new device-type source of truth? Will that be a contract type we could leverage here and remove these files?

@vipulgupta2048 This PR looks good to me, we can merge and maybe open a new issue to replace this bit entirely?

**Review by klutchell — APPROVED** [review]

**Comment by vipulgupta2048** [comment]
True that @lurch the arch property is only being used in one place indeed within a balena push out specifically. Would be good to find a solution for that and clean that as well. 

@klutchell Indeed in our conversation with @mehalter my plan is to fully wipe out both `device.json` and `language.json` dictionaries and have them auto-generated using contracts. I found these properties to be obsolete now and decided to remove them to give us a clear path on knowing what data we have and what we don't have. Good news: We have everything to auto-generate all the properties even instructions. 

We can't automate them just yet though because we also need to complete work on screenshots automation for the getting-started guide. With both tasks done + the renovation of getting started guides being done in #2060 we will be in great shape for fully automating the new and improved getting started for the years to come. Check out draft vision: https://docs.google.com/document/d/1oHzkmH_kC6-Z0m7ju5szKDEqE9d_MjhnfY83I2iHgvg/edit#

**Pull request merged**
