### PR TITLE
Correct supported devices list links fixes #1682

### LINKED ISSUE #1682: Markdown for supported devices list on some device types in getting started guide is not parsed
Screenshot 2021-03-19 at 16 18 16

### PR DESCRIPTION
**Pull request by chrisys**
Change-type: patch
Signed-off-by: Chris Crocker-White <chriscw@balena.io>

### CODE REVIEW

**Comment by chrisys** [comment]
@balena-ci I self-certify!

**Comment by vipulgupta2048** [comment]
@chrisys No linked issues, no balenaCoins for you :smiling_imp:

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Pull request merged**
