### PR TITLE
Add Connect Core 8X Pro images

### PR DESCRIPTION
**Pull request by acostach**
Fixes https://github.com/balena-io/docs/issues/1662

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Looking good @acostach Thanks! Like always, I have created a deploy for you. If it look good, ship it 🚀

**Comment by acostach** [comment]
Sure, I moved them up @vipulgupta2048

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Pull request merged**
