### PR TITLE
Delete Post-provisioning image from Docs repo

### PR DESCRIPTION
**Pull request by dtischler**
Removed the post-provisioning image as it is outdated.

Change-type: patch

### CODE REVIEW

**Comment by dtischler** [comment]
@balena-ci I self-certify

**Comment by dtischler** [comment]
@balena-ci I self-certify!

**Review by vipulgupta2048 — APPROVED** [review]

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Pull request merged**
