### PR TITLE
Removing external docs from docs repo

### PR DESCRIPTION
**Pull request by garethtdavies**
Change-type: patch
Signed-off-by: Gareth Davies gareth@balena.io

### CODE REVIEW

**Comment by garethtdavies** [comment]
@balena-ci retest

**Comment by garethtdavies** [comment]
This related PR https://github.com/balena-io/docs/pull/1211 hides the "Improve this doc" link for these external docs. Ideally, these will be linked to the correct upstream repo though this will involve a bit more effort to implement.

**Comment by garethtdavies** [comment]
See also #1211 as this now correctly links to the corresponding external repo for "Improve this doc"

**Comment by garethtdavies** [comment]
@shaunmulligan yes, those docs are in #1211. I'll merge them both together as #1211 fixes the "Improve this doc" issue that this one creates.

**Comment by shaunmulligan** [comment]
@garethtdavies awesome, sounds good !

**Comment by garethtdavies** [comment]
@balena-ci retest

**Comment by garethtdavies** [comment]
@balena-ci retest

**Pull request merged**
