### PR TITLE
docs: Rename resin-supervisor to balena-supervisor

### PR DESCRIPTION
**Pull request by klutchell**
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Linked it to an issue @klutchell if you want to expand the PR. The other `RESIN` occurrences are in OS docs. Maybe another PR?

**Comment by vipulgupta2048** [comment]
I was thinking to clean up resin out of docs.

**Comment by klutchell** [comment]
@vipulgupta2048 I think I would prefer another PR to focus specifically on `RESIN_` config vars. I can remove the `RESIN_SUPERVISOR_` changes from this PR and just focus on `resin-supervisor` if that sounds good?

**Review by vipulgupta2048 — APPROVED** [review]

**Comment by vipulgupta2048** [comment]
@klutchell  Another PR to get replace RESIN_ variables sound good. Unlinking the PR for you to create your PR and then link to it then.

**Comment by klutchell** [comment]
Opened https://github.com/balena-io/docs/pull/1908 to make the `RESIN_` env var changes.

**Pull request merged**
