### PR TITLE
Update dockerfile.md

### PR DESCRIPTION
**Pull request by derekclair**
Component: Update Docs 
Add escape character to `Dockerfile.<extension>`, otherwise they're not visible. (They're being parsed as inline markup, and thus not rendering in the text.)
Change-type: patch

### CODE REVIEW

**Comment by garethtdavies** [comment]
@balena-ci retest

**Comment by garethtdavies** [comment]
Hi @derekclair this needs rebasing on master so it can be merged. I can do this for you but you'll need to "allow edits from maintainers" to your PR https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by derekclair** [comment]
@garethtdavies if you wouldn't mind that would be fantastic. Thank you! (That should be done, just the little checkbox I presume, which, reads ☑️ on my end.)

**Comment by garethtdavies** [comment]
@derekclair that did it, thanks 😄

**Comment by derekclair** [comment]
@balena-ci retest

**Pull request merged**
