### PR TITLE
Anonymize GoSquared IP collection

### PR DESCRIPTION
**Pull request by thundron**
Change-type: patch
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@balena-ci rebase
@thundron Is this good to go?

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by thundron** [comment]
@vipulgupta2048 I think so, that parameter should be the only thing needed afaik

**Comment by thundron** [comment]
@balena-ci rebase

**Comment by thundron** [comment]
@balena-ci I self-certify!

**Pull request merged**
