### PR TITLE
Patch: Correct typo in offline updates

### PR DESCRIPTION
**Pull request by Stefsak**

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@Stefsak One really shouldn't be merging PR's before the checks have been completed. The correct flow is either the contributor themselves approve their own PR with the `@balena-ci I self-certify!` command (Only if they are a team member) or a reviewer approving the PR. Only after approval from at least one of the above, the balena-bulldozer makes sure everything is alright. When the tests pass, then only a PR is merged automatically by the balena-bulldozer.

**Comment by lurch** [comment]
P.S. Hi Stefanos! :wave:

**Comment by Stefsak** [comment]
Hey Andrew!!!

Hope all is well with you 😜😜😜

**Comment by vipulgupta2048** [comment]
@lurch This was an edge case scenario that has been addressed and resolved. We do have a protected branch workflow already in place.

**Pull request merged**
