### PR TITLE
release-policy: Update instructions to set fleet release policy

### PR DESCRIPTION
**Pull request by klutchell**
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>
Resolves: https://github.com/balena-io/docs/issues/2067

### CODE REVIEW

**Comment by klutchell** [comment]
I don't love the screenshot I grabbed here. I wanted to capture the fact that we were in the summary tab, but it's not obvious that the Releases field is on the far right.

I also didn't do anything special with the screenshot to make it "web ready". Do we have size and quality guidelines?

**Comment by vipulgupta2048** [comment]
@klutchell Thanks for the PR, what you can improve in your screenshot is capture the shot with higher quality preferably on a monitor with zoomed in UI. Next, to indicate clearly what page you are on or what folks should be clicking on. You can edit the picture to draw red rectangles on the menus.

**Review by vipulgupta2048 — COMMENTED** [review]
@klutchell Thanks for the PR, what you can improve in your screenshot is capture the shot with higher quality preferably on a monitor with zoomed in UI. Next, to indicate clearly what page you are on or what folks should be clicking on. You can edit the picture to draw red rectangles on the menus. You were right to not go for a GIF here, as it is a lot of work to record and edit a GIF and they are not as maintainble.

**Comment by klutchell** [comment]
Superseded by https://github.com/balena-io/docs/pull/2393

**Pull request closed without merging**
