### PR TITLE
Update logo to svg

### PR DESCRIPTION
**Pull request by shawaj**
Update logo to new svg

Change-type: patch
Signed-off-by: Aaron Shaw <shawaj@gmail.com>

### CODE REVIEW

**Comment by shawaj** [comment]
As discussed on Flowdock with @iamsolankiamit

**Comment by iamsolankiamit** [comment]
@shawaj I just realised, I had already opened a PR for this change. I'll close mine, no worries.

**Comment by shawaj** [comment]
@iamsolankiamit no worries - I just noticed that too!

**Comment by vipulgupta2048** [comment]
@shawaj There is also a PR changing the same file by @andrewnhem in #1533. Is it safe to assume your PR is the superset of them all and can be merged right?

**Comment by shawaj** [comment]
@vipulgupta2048 ahh yes - looks like mine only differs from @andrewnhem in that I added some text explaining you could still use the .png

**Comment by andrewnhem** [comment]
Haha my bad, all. I was seeing what it was like as a user who clicks on "Improve this doc" and kinda went through the motions. I shoulda checked existing PRs.

**Comment by shawaj** [comment]
@andrewnhem I did exactly the same to @iamsolankiamit 👍

**Review by vipulgupta2048 — COMMENTED** [review]
@shawaj Cool, will approve once the commit is formatted right. I think you need to leave a line between the commit body and footer tags.

**Comment by shawaj** [comment]
> @shawaj Cool, will approve once the commit is formatted right. I think you need to leave a line between the commit body and footer tags.

All done @vipulgupta2048 👍

**Review by vipulgupta2048 — APPROVED** [review]

**Pull request merged**
