### PR TITLE
Update npm dependencies

### PR DESCRIPTION
**Pull request by 20k-ultra**
Change-type: patch
Signed-off-by: 20k-ultra <3946250+20k-ultra@users.noreply.github.com>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by 20k-ultra** [comment]
@balena-ci retest

**Review by vipulgupta2048 — COMMENTED** [review]
LGTM - apart from the build failing. I think this is good to go.

**Comment by vipulgupta2048** [comment]
@20k-ultra Check out, https://ci.product-os.io/builds/593130 I think one of the build dependencies missing

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
Repinging @20k-ultra

**Comment by 20k-ultra** [comment]
@balena-ci I self-certify!

**Comment by 20k-ultra** [comment]
I ran this locally and looks good

**Pull request merged**
