### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**
Fix typos
Change-type: patch
Signed-off-by: Dimitris Apostolou dimitris.apostolou@icloud.com

### CODE REVIEW

**Comment by xginn8** [comment]
Hi @rex4539 and thanks for contributing! The changes lgtm, but you'll need to modify the commit itself to add the footers that you added in the message above. Once you do that, the CI should pass.

**Comment by garethtdavies** [comment]
@balena-ci retest

**Comment by garethtdavies** [comment]
@balena-ci retest

**Comment by garethtdavies** [comment]
Hey @rex4539, good to see you here. I think you are just missing the brackets on that commit message that's causing this to still fail e.g.

```
Change-type: patch
Signed-off-by: Dimitris Apostolou <dimitris.apostolou@icloud.com>
```

**Comment by garethtdavies** [comment]
@balena-ci retest

**Comment by garethtdavies** [comment]
@balena-ci retest 

(trying to look at logs to see why this is failing)

**Comment by garethtdavies** [comment]
So this looks to be a line-ending problem as it's complaining about this being on a single line:

`Fix typos Change-type: patch Signed-off-by: Dimitris Apostolou <dimitris.apostolou@icloud.com>`

Rather than continue to back and forth on this, I'm just going to edit this commit message and push back up so it can be merged but for any future contributions @rex4539 something to bear in mind. We're also having internal discussions over how to simplify this process for external contributors 👍

**Comment by garethtdavies** [comment]
@balena-ci retest

**Comment by lurch** [comment]
> We're also having internal discussions over how to simplify this process for external contributors :+1: 

It might be nice if some of the results of the ResinCI checks were publicly viewable? :man_shrugging:

**Comment by garethtdavies** [comment]
Thanks for the suggestion. I think for other repos where the test failures are more meaningful that would help. What I am getting at here is sensible defaults or the ability for maintainers to use labels to indicate change type for those users who don't include a commit footer at all. PR templates would probably help here too.

**Pull request merged**
