### PR TITLE
Improve spacing of lists

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by Page-** [comment]
I chose 16px top/bottom to match what github uses for its rendered markdown. It looks good to me on the pages I've looked at but I haven't checked every single page

**Comment by Page-** [comment]
Before:
image

After:
image

**Comment by vipulgupta2048** [comment]
Looking good @Page- My eyes already feel better watching this. Please do self-certify if the change is good.

**Comment by gantonayde** [comment]
We can also match the spacing between the first and second pair of sub-bullet points by moving the code block one line up.

bullets

**Comment by gantonayde** [comment]
Okay, I see the `cli.markdown` is pulled from another repo so it needs a separate PR.

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci I self-certify!

**Pull request merged**
