### PR TITLE
Update/switch to @balena/doxx, picking up a lot of nested changes

### PR DESCRIPTION
**Pull request by Page-**
Update @balena/doxx from 0.11.5 to 1.0.0

Change-type: patch

### CODE REVIEW

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci I self-certify!

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@Page- for some reason the ResincCI check isn't finishing. Will have to check this out after support, maybe some dependency issue

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci rebase

**Pull request merged**
