### PR TITLE
patch: Updating the outdated screencaps in Account Management

### PR DESCRIPTION
**Pull request by mpous**
Updated screencaps from the Access Tokens. 

Need to check the widths of the screencaps once on production with different browsers.

### CODE REVIEW

**Comment by mpous** [comment]
@vipulgupta2048 just created a new PR as i couldn't ammend the commit message!

**Comment by stathismor** [comment]
@balena-ci retest

**Comment by vipulgupta2048** [comment]
@balena-ci retest

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@stathismor it's not working still

**Comment by stathismor** [comment]
@balena-ci rebase

**Comment by stathismor** [comment]
@vipulgupta2048, issue is still with commit having two spaces after the colon (GitHub UI differs from git log). Needs to be amended and pushed again. @mpous has created another branch for this, we can probably close this one now. Also, I have created an issue to make the `versionist` a bit more forgiving https://github.com/product-os/versionist/issues/191

**Comment by vipulgupta2048** [comment]
Thanks, @stathismor for the assist. I will wait for his new PR before closing this. 
cc: @mpous

**Comment by vipulgupta2048** [comment]
@mpous Friendly reminder to close this out and create that new PR, as Stathis suggested

**Pull request closed without merging**
