### PR TITLE
Added notes to explain Heartbeat and VPN Only Online status types

### PR DESCRIPTION
**Pull request by 20k-ultra**
depends-on: https://github.com/balena-io/debugging-masterclass/pull/30

### CODE REVIEW

**Comment by 20k-ultra** [comment]
@cywang117

**Comment by vipulgupta2048** [comment]
@20k-ultra @cywang117 We already have a PR open by @srlowe #1869 working on this page. There's also a discussion going on how we can effectively improve device statuses. Check out https://www.flowdock.com/app/rulemotion/r-beginners/threads/Mv9usxt9Ryr56qAtLk2DYXoli8I

**Comment by cywang117** [comment]
@20k-ultra Want to close this and add any info as a comment / suggestion to Scott's PR? #1869

**Comment by 20k-ultra** [comment]
leaving open as a  possible candidate. Especially because this uses another [pr](https://github.com/balena-io/debugging-masterclass/pull/30) which I think is a nice connection.

**Comment by 20k-ultra** [comment]
closing in favour of https://github.com/balena-io/docs/pull/1869 

cc @srlowe. Take as much parts that you like from this PR to use in yours :)

**Pull request closed without merging**
