### PR TITLE
Fix $names.company to $names.company.upper

### PR DESCRIPTION
**Pull request by rahul-thakoor**
Change-type: patch
Signed-off-by: Rahul Thakoor <rahul@balena.io>

### CODE REVIEW

**Comment by rahul-thakoor** [comment]
@balena-ci rebase

**Comment by rahul-thakoor** [comment]
this shouldn't receive coins 😅

**Comment by rahul-thakoor** [comment]
@balena-ci I self certify!

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Pull request merged**
