### PR TITLE
fix link

### PR DESCRIPTION
**Pull request by shawaj**
fix broken link

### CODE REVIEW

**Review by xginn8 — APPROVED** [review]
lgtm, just needs a properly formatted commit to merge! you need a footer with a `Change-type: {patch|minor|major}`

**Comment by shawaj** [comment]
@xginn8 guess I should have read the contribution guidelines first :-)

Should be fixed now in any case!

**Comment by shawaj** [comment]
@balena-ci retest

**Comment by xginn8** [comment]
I think the CI is confused by your `component: fix link` almost-footer. you can move that to the first line or just drop it entirely and i suspect CI will pass.

**Comment by shawaj** [comment]
@xginn8 yep that seemed to sort it. thanks!

**Pull request merged**
