### PR TITLE
Update screenshots for Change App Types

### PR DESCRIPTION
**Pull request by andreas-metaxas**
*Please check the [CONTRIBUTING.md](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) 
file for relevant information on contributing to the documentation.*

Thank you very much for your contribution!

### CODE REVIEW

**Review by vipulgupta2048 — CHANGES_REQUESTED** [review]
@andreas-metaxas Please follow the instruction mentioned in the Contributing guide to add images - https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md#adding-imagesscreenshots-to-the-docs 
Also, do make sure to add images with the same name as the ones you are replacing in order to make no changes in the markdown document where these images might be getting referenced.

**Comment by andreas-metaxas** [comment]
> @andreas-metaxas Please follow the instruction mentioned in the Contributing guide to add images - https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md#adding-imagesscreenshots-to-the-docs
> Also, do make sure to add images with the same name as the ones you are replacing in order to make no changes in the markdown document where these images might be getting referenced.

@vipulgupta2048 I have followed the same path as the instructions mentioned.  From my Github desktop, I cloned the idocs repo then I created a brunch-show in folder and then static-img-common-app and then I renamed the new screenshot exactly as the old one "create_app". Pls guide me through my mistake because I cannot understand it. Thanks

**Comment by vipulgupta2048** [comment]
No worries at all @andreas-metaxas Happy to help. In the screenshot below, as i can see from the [files changed](https://github.com/balena-io/docs/pull/1831/files) section. 

The first image you uploaded is somehow been uploaded inside the `shared` directory. The image needs to be uploaded here in the `static/image/common/app` directory as mentioned in the contributing document. Not sure what you mean `created a brunch-show in folder`. Moreover, this image that you uploaded isn't of the same name as `create_app.png` which is what I meant in my message above. 

Also, please do check the [screenshot you uploaded](https://raw.githubusercontent.com/balena-io/docs/165e9ae627ed0693d2dbf335667af113b517405b/shared/Create-application.png) as the quality of the image is very low. While taking the screenshot do make sure to remove any personally identifiable information such as your balenaCloud username. Create a dummy organization instead and click the screenshot using that with some fields filled for users to know what information needs to be provided.

The other 2 images below have been deleted but weren't replaced by the updated screenshots. Are you missing a commit or some update that was meant to be done but hasn't been pushed yet? Please do check, also reach out for more questions. I will be happy to help. 

Screenshot from 2021-04-13 13-32-12

**Comment by andreas-metaxas** [comment]
> No worries at all @andreas-metaxas Happy to help. In the screenshot below, as i can see from the [files changed](https://github.com/balena-io/docs/pull/1831/files) section.
> 
> The first image you uploaded is somehow been uploaded inside the `shared` directory. The image needs to be uploaded here in the `static/image/common/app` directory as mentioned in the contributing document. Not sure what you mean `created a brunch-show in folder`. Moreover, this image that you uploaded isn't of the same name as `create_app.png` which is what I meant in my message above.
> 
> Also, please do check the [screenshot you uploaded](https://raw.githubusercontent.com/balena-io/docs/165e9ae627ed0693d2dbf335667af113b517405b/shared/Create-application.png) as the quality of the image is very low. While taking the screenshot do make sure to remove any personally identifiable information such as your balenaCloud username. Create a dummy organization instead and click the screenshot using that with some fields filled for users to know what information needs to be provided.
> 
> The other 2 images below have been deleted but weren't replaced by the updated screenshots. Are you missing a commit or some update that was meant to be done but hasn't been pushed yet? Please do check, also reach out for more questions. I will be happy to help.
> 
> Screenshot from 2021-04-13 13-32-12

Pls @vipulgupta2048, I made some changes to check if everything is ok. Also, you were right, there was an img in the shared file but I deleted it and renamed the png img`create_app.png` in the common-app file that I already had an updated photo form the first time. Sorry man and thanks for all your help.

**Comment by andreas-metaxas** [comment]
> No worries at all @andreas-metaxas Happy to help. In the screenshot below, as i can see from the [files changed](https://github.com/balena-io/docs/pull/1831/files) section.
> 
> The first image you uploaded is somehow been uploaded inside the `shared` directory. The image needs to be uploaded here in the `static/image/common/app` directory as mentioned in the contributing document. Not sure what you mean `created a brunch-show in folder`. Moreover, this image that you uploaded isn't of the same name as `create_app.png` which is what I meant in my message above.
> 
> Also, please do check the [screenshot you uploaded](https://raw.githubusercontent.com/balena-io/docs/165e9ae627ed0693d2dbf335667af113b517405b/shared/Create-application.png) as the quality of the image is very low. While taking the screenshot do make sure to remove any personally identifiable information such as your balenaCloud username. Create a dummy organization instead and click the screenshot using that with some fields filled for users to know what information needs to be provided.
> 
> The other 2 images below have been deleted but weren't replaced by the updated screenshots. Are you missing a commit or some update that was meant to be done but hasn't been pushed yet? Please do check, also reach out for more questions. I will be happy to help.
> 
> Screenshot from 2021-04-13 13-32-12

@vipulgupta2048 At first I did a mistake by adding the img in a shared file but then after @konmouz had helped me I found the right path and as I am looking now it was the right path, static-img-common-app, and the img is create_app. I am sorry but just now I saw that I hadn't deleted the old screenshot in the shared file. Pls, check if a PR has created for the deleted img.

**Comment by lurch** [comment]
According to the "files changed" tab at the top of this page, you've now added an image called `static/img/common/app/create_app.png.png` which probably isn't right?

P.S. "change app tyres"  :laughing: :car:

**Comment by andreas-metaxas** [comment]
> According to the "files changed" tab at the top of this page, you've now added an image called `static/img/common/app/create_app.png.png` which probably isn't right?
> 
> P.S. "change app tyres" 😆 🚗 🔧

Oops!! Sorry man.

**Review by vipulgupta2048 — CHANGES_REQUESTED** [review]
@andreas-metaxas Thanks, it's getting there. Couple of suggestions. 
1. Not sure why but the screenshot you are taking is getting optimized for some reason the quality is passable but could be better. Can you trim the borders of the screenshot, we only need the Create Application modal in the screenshot and not much else.
2. Is there a reason why you have deleted this static/img/common/create-application.png

**Comment by andreas-metaxas** [comment]
> @andreas-metaxas Thanks, it's getting there. Couple of suggestions.
> 
> 1. Not sure why but the screenshot you are taking is getting optimized for some reason the quality is passable but could be better. Can you trim the borders of the screenshot, we only need the Create Application modal in the screenshot and not much else.
> 2. Is there a reason why you have deleted this static/img/common/create-application.png

@vipulgupta2048 I don't understand what you mean by having deleted the static/img/common/create-application.png.
Guide me through cause maybe I did something that I didn't mean it.

**Comment by andreas-metaxas** [comment]
> > @andreas-metaxas Thanks, it's getting there. Couple of suggestions.
> > 
> > 1. Not sure why but the screenshot you are taking is getting optimized for some reason the quality is passable but could be better. Can you trim the borders of the screenshot, we only need the Create Application modal in the screenshot and not much else.
> > 2. Is there a reason why you have deleted this static/img/common/create-application.png
> 
> @vipulgupta2048 I don't understand what you mean by having deleted the static/img/common/create-application.png.
> Guide me through cause maybe I did something that I didn't mean it.

Check now man I think we are ok. @vipulgupta2048

**Comment by vipulgupta2048** [comment]
> what you mean by having deleted the static/img/common/create-application.png

@andreas-metaxas In the screenshots below, as i can see from the [files changed](https://github.com/balena-io/docs/pull/1831/files) section.

There is an image that has been deleted which is located here https://github.com/balena-io/docs/blob/master/static/img/common/create-application.png, I don't think you meant to delete this image in your PR. You can see with the red color it shows, it means that the file it is referring to has been deleted or modified. I am trying to understand the reason for deleting this file. If there isn't one we need to restore it. Let me know if this helps! Thanks 

Screenshot from 2021-04-15 01-13-02

Another screenshot to help you see specifically which image (static/img/common/create-application.png) I am talking about what I am talking about. 

Screenshot from 2021-04-15 01-08-53

**Comment by andreas-metaxas** [comment]
> > what you mean by having deleted the static/img/common/create-application.png
> 
> @andreas-metaxas In the screenshots below, as i can see from the [files changed](https://github.com/balena-io/docs/pull/1831/files) section.
> 
> There is an image that has been deleted which is located here https://github.com/balena-io/docs/blob/master/static/img/common/create-application.png, I don't think you meant to delete this image in your PR. You can see with the red color it shows, it means that the file it is referring to has been deleted or modified. I am trying to understand the reason for deleting this file. If there isn't one we need to restore it. Let me know if this helps! Thanks
> 
> Screenshot from 2021-04-15 01-13-02
> 
> Another screenshot to help you see specifically which image (static/img/common/create-application.png) I am referring to.
> 
> Screenshot from 2021-04-15 01-08-53

But the Screenshot with the red letters is the old one and the other is new. @vipulgupta2048 
You told me to replace it am I right? Probably I am something missing here man and cannot understand it correctly.

**Comment by andreas-metaxas** [comment]
@balena-ci I self-certify!

**Review by vipulgupta2048 — APPROVED** [review]

**Comment by lurch** [comment]
Just out of curiosity, I just made a local clone of this repo, and it looks like `create-application.png` might not actually be used anywhere? :shrug: 
```bash
$ git grep 'create_app.png'
pages/learn/manage/app-types.md:<img src="/img/common/app/create_app.png" width="80%">
$ git grep 'create-application.png'
$
```

**Comment by vipulgupta2048** [comment]
@lurch Yep, I wanted to keep the PR in scope and wanted the contributor to understand why we are not deleting the image. There will be more images in the docs that are still present but not being used anywhere. Wonder if there's a tool to find unused images/assets?

**Comment by lurch** [comment]
> Yep, I wanted to keep the PR in scope and wanted the contributor to understand why we are not deleting the image.

:+1: 

> Wonder if there's a tool to find unused images/assets?

Images (that do exist) aren't visible when the pages are viewed via GH e.g. https://github.com/balena-io/docs/blob/master/pages/learn/manage/app-types.md (presumably due to the way that things get re-arranged when deploying to the server) so I suspect you'd probably need to write a custom little script for that?

**Comment by vipulgupta2048** [comment]
Seems like it @lurch Can you open a issue for it so at least this gets tracked.

**Comment by lurch** [comment]
I'm happy to leave little comments on other issues that I see in passing, but I don't really have the time to go creating new issues myself. I'll leave that up to the Balena staff... :wink:

**Pull request merged**
