### PR TITLE
Added Jetson Xavier NX SD-Card Device Type

### PR DESCRIPTION
**Pull request by dtischler**
Added Jetson Xavier NX SD-Card Device Type for Getting Started Guide, re-using the Jetson Nano as a starting point.

Change-type: patch 
Signed-off-by: David Tischler david@balena.io

### CODE REVIEW

**Review by vipulgupta2048 — COMMENTED** [review]
@dtischler You alread opened a pull request for this. Close the other way please. 

Thanks, your sincerely 
Overworked humans.

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by vipulgupta2048** [comment]
@klutchell Determination :100:

**Review by vipulgupta2048 — COMMENTED** [review]
@dtischler Are you planning to add more to this PR? Though I would recommend closing this PR as we move towards automating the Getitng Guides instead.

**Comment by dtischler** [comment]
Let's close this, I agree, it sounds like the process is going to change / improve.

**Pull request closed without merging**
