### PR TITLE
Updated analytics-client version

### PR DESCRIPTION
**Pull request by laziob**
Also added Navigation Click tracking for links to githubMain URL
such as Improve this Doc button.

Change-type: Minor
Signed-off-by: Ezequiel Boehler ezequiel@balena.io

*Please check the [CONTRIBUTING.md](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) 
file for relevant information on contributing to the documentation.*

Thank you very much for your contribution!

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@balena-ci retest

**Comment by iamsolankiamit** [comment]
@balena-ci rebase

**Review by vipulgupta2048 — COMMENTED** [review]
@laziob @iamsolankiamit I am assuming this is good to go. Do self-certify this when you see it.

**Comment by laziob** [comment]
@balena-ci rebase

**Comment by laziob** [comment]
@balena-ci I self-certify!

**Pull request merged**
