### PR TITLE
Updated the Fleet Xfer Docs

### PR DESCRIPTION
**Pull request by rhampt**
Includes more information that customers ask about a pending transfer

Change-type: patch
Signed-off-by: Ryan Hampton (@rhampt) <rhampt@balena.io>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by rhampt** [comment]
@balena-ci I self-certify!

**Comment by rhampt** [comment]
My markdown best practices auto-formatter kicked in in VS code on save. Looks like it transitioned italics to using _ instead of *.

**Comment by vipulgupta2048** [comment]
@rhampt That's a pretty bold assumption for a formatter to take. I see what it wanted to do since `_This_` is equal to this `*this*` in markdown. But, not in docs where having __Note:__ will create a special yellow note box. I am reverting this PR. Please make a new PR with the changes you intend to make.

**Comment by rhampt** [comment]
@vipulgupta2048 Grrr I always get something wrong. I need to just turn off my auto formatter when working on balena docs. Thanks for reverting

**Comment by vipulgupta2048** [comment]
Hey man, I didn't mean it like that. Reverting is an escape hatch meant for a reason to safely pull back the branch back to the previous state. It isn't necessarily bad and definitely not something to feel bad about. Things happen, we can't control all the time. You were the one who actually caught it for us to revert the change. Now, we can make it right 👍🏼 

What formatter do you use? And is there a specific reason why you use a formatter for Markdown? I didn't know there was a need for things to be formatted in Markdown. What exactly does it do?

**Comment by rhampt** [comment]
@vipulgupta2048 I appreciate your comment! I was just annoyed at myself because I realized as I pushed my commits up to remove that I didn't check my diffs first. I was an active software engineer for about 5 years, and (at least then) knew git pretty darn well. But I've not yet familiarized myself with balena coding/docs standards as well as I've had liked.

I've been trying to make sure I contribute to docs whenever a customer comes along with questions that fit some structure already in place (in this case questions about fleet IDs during xfer), but I was lazy in thinking I could bust it out in 5min. I should have followed up my first commit with one that removed my auto-formatted updates before merging. I thought to do it and just didn't because I didn't think it mattered. 🤷‍♂️ 

For markdown in my VS-code env, I use these two popular extensions:
- https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one&ssr=false#review-details
- https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint&ssr=false#review-details

I use auto formatters for all the programming languages I use. It just became part of my workflow not to care about my text structure since I Ctrl-S and the text shapes up properly/consistently. Do you use any auto-formatters—not for markdown of course, but for other structured text like code?

**Comment by klutchell** [comment]
+1 for Markdownlint in vscode, I use it all the time. I know it can wreak havoc on the toc in our docs though so I explicitly disabled reformatting of toc in the settings.

**Comment by rhampt** [comment]
@klutchell @vipulgupta2048  Maybe we should Markdownlint all our docs at once to unify the structure 🤔

It could even be in the docs readme to follow a consistent format (maybe just default Markdownlint or tweaking [the rules](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint&ssr=false#overview) to your liking).

**Comment by vipulgupta2048** [comment]
(@)hubot, we don't pay you enough to do provide this info on Github PR's? Get a life, please.

**Comment by klutchell** [comment]
> [hubot] klutchell is on leave today, returning to work Monday the 1st

Not to mention that my day off is tomorrow, not today. Figure it out HB

**Comment by vipulgupta2048** [comment]
While, I use yzhang's Markdown all in one too. I am still not seeing what's there to lint in Markdown except a little indentation, 
and removal of whitespace (but that too not everywhere). Sure, there might be ways to globally apply linter rules using specific configurations files or even have a PR to lint the entire docs with markdownlint but I like to see the results for myself for that. 

If we do make linting markdown part of our "rules", then I recommend adding this point to our #1877

**Comment by klutchell** [comment]
Here's the spec, there is a surprising number of rules regarding whitespace, bullets, headings, code blocks, etc.

https://spec.commonmark.org/0.30/

Some things I like about it off the top of my head:
- noticing if I've skipped a heading level (went from `##` to `####` without `###`)
- making sure I'm not mixing `*` and `-` for bullets
- whitepace around everything, code blocks, lists, etc
- automatic table formatting
- raw urls should be wrapped with `< >`

**Pull request merged**
