### PR TITLE
Update base images docs

### PR DESCRIPTION
**Pull request by nghiant2710**
Update stack versions to match with latest changes in contracts

Change-type: patch
Signed-off-by: Trong Nghia Nguyen <nghiant2710@gmail.com>

### CODE REVIEW

**Review by dfunckt — APPROVED** [review]
Nice one @nghiant2710!

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@nghiant2710 this has conflicts that need resolving

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Review by vipulgupta2048 — COMMENTED** [review]
@nghiant2710 Thanks for contributing, please resolve the conflicts in your PR and optionally link the issue you were resolving

**Comment by nghiant2710** [comment]
@vipulgupta2048, done :)

**Comment by dfunckt** [comment]
@nghiant2710 please rebase properly -- merging master onto your branch messes up history and I don't see how this is acceptable.

**Pull request merged**
