### PR TITLE
Document that Operators can manage provisioning API keys

### PR DESCRIPTION
**Pull request by thgreasi**
Change-type: minor
See: https://github.com/balena-io/balena-api/pull/3232
HQ: https://jel.ly.fish/e450713f-001c-4470-b571-71724aeb0869
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Review by klutchell — APPROVED** [review]
lgtm

**Comment by klutchell** [comment]
@balena-ci rebase

**Comment by thgreasi** [comment]
:pray: :heart: @klutchell

**Comment by thgreasi** [comment]
@balena-ci retest

**Pull request merged**
