### PR TITLE
WIP meta: Adding support for copying a code block

### PR DESCRIPTION
**Pull request by garethtdavies**
Quick Hack Friday project implementing a copy code button based on the Docusaurus implementation here https://gist.github.com/yangshun/55db997ed0f8f4e6527571fc3bee4675. Simply adds a Copy button to any fenced code block as shown below.

copy-code

Change-type: patch
Connects-to: #633
Signed-off-by: Gareth Davies <gareth@balena.io>

### CODE REVIEW

**Comment by karaxuna** [comment]
Hi @garethtdavies , why was this closed?

**Comment by karaxuna** [comment]
Hi @garethtdavies , why was this closed?

**Comment by garethtdavies** [comment]
Hey, I can't recall why I closed it but likely as was a hack Friday project and so closed it before I left as it wasn't merged?

**Comment by vipulgupta2048** [comment]
This is pretty neat to keep around though
@garethtdavies We can take it ahead if the code you added made it work.

**Pull request closed without merging**
