### PR TITLE
Adding version numbers to Ubuntu versions

### PR DESCRIPTION
**Pull request by drjasonharrison-vp-eio**
component: Add version numbers to Ubuntu version names

Change-type: patch
Signed-off-by: Jason Harrison <jason@eiodiagnostics.com>

### CODE REVIEW

**Comment by drjasonharrison-vp-eio** [comment]
@xginn8 thanks, I have edited the description here on github. Don't know if that will work. Oh how I wish github allowed more server side hooks.

**Comment by lurch** [comment]
IIRC you need to edit the actual commit-message, rather than just editing the PR description.

**Comment by xginn8** [comment]
@drjasonharrison-vp-eio yep what lurch said is true, you'll need to edit your commit message (`git commit --amend`) and then push it up again `git push --force-with-lease`. If you like, I can also just take over the commit and fix it up for you.

**Comment by drjasonharrison-vp-eio** [comment]
I made the changes through the online github interface, so yes, please take it over. Thanks!

**Comment by xginn8** [comment]
@drjasonharrison-vp-eio can you just confirm that the "Allow edits from maintainers" box is checked for this PR (https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by xginn8** [comment]
Never mind, I've confirmed it myself. Thanks again for contributing @drjasonharrison-vp-eio!

**Comment by xginn8** [comment]
@balena-ci retest

**Pull request merged**
