### PR TITLE
Remove unused assets

### PR DESCRIPTION
**Pull request by JSReds**
Remove unused assets

Resolves: #1859
Change-type: patch
Signed-off-by: Andrea Rosci <andrear@balena.io>

I wrote a parser that check which assets are unused. Those found seem to me to be really many, so I would like to calmly check if correct.

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by JSReds** [comment]
Running the DOCS locally everything works fine, with all the images. I hope no external project uses these images :)

**Comment by vipulgupta2048** [comment]
@JSReds This such good PR but you raise a fair point. Is there any way for us to check about that? We can do a team ping for folks to make a note about this?

**Comment by vipulgupta2048** [comment]
Hey @JSReds just an update on this PR. I did check on the Heroku dashboard and there isn't a way to check the requests that the server is getting. I am actually thinking to hold this PR for a bit, as we go around generating the getting started guides from contracts. These image might serve to be useful inside contracts to someone else in a later stage. If they are not, we can surely remove them. Atm let's keep them and around revisit this work when that task is done.

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Review by vipulgupta2048 — APPROVED** [review]

**Comment by vipulgupta2048** [comment]
Thanks for all the hard work @JSReds Found something else in the docs.

**Pull request merged**
