### PR TITLE
patch: Fix etcher link in instructions

### PR DESCRIPTION
**Pull request by thundron**

### CODE REVIEW

**Review by vipulgupta2048 — COMMENTED** [review]
Hey @thundron if you are correcting the link for this device-type the link would be wrong almost every other device-type as well. Can you please correct them throughout the file as well. Thanks!

**Comment by lurch** [comment]
Only a minor point, but I just noticed that some entries say "Write the OS file you downloaded to an SD card..." whereas others say "Write the OS file you downloaded to your SD card...".

**Comment by vipulgupta2048** [comment]
@thundron ?

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
Will address the consistency in another PR

**Comment by 20k-ultra** [comment]
@balena-ci rebase

**Review by 20k-ultra — APPROVED** [review]

**Pull request merged**
