### PR TITLE
patch: Update Wifi USB Dongle to network adapters list

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Solves #2395, add USB dongles and modems to the list

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@alexgg @majorz This PR can be used as a reference to do future changes related to bringing information from meta-balena. 
This information will stay updated as long as the headings on meta-balena readme aren't moved or changed. This is critical for it to work. 

Please review the information already on the docs about wifi adapters and let me know if I should remove it or keep it there. It lists more wifi adapters that are not listed on the meta-balena readme.

**Comment by alexgg** [comment]
@vipulgupta2048 some comments.

I think we should only list devices that we actually verify, otherwise they can silently break or become unsupported.

To this extend, the source of truth should be the lists in the meta-balena README. We also have to make sure all the devices in there are actually reflected in at least one device type in the rack.

There is a section that says:
```
Here are some notable devices known to work:

[Pi Hut USB WiFi Adapter](http://thepihut.com/products/usb-wifi-adapter-for-the-raspberry-pi) - Small form-factor and works right out of the box!
[TP-Link WN725N](https://www.amazon.com/TP-Link-wireless-network-Adapter-SoftAP/dp/B008IFXQFU) - Small, reliable and cheap TP Link device.
[TP-Link AC600](https://www.amazon.com/TP-Link-Mini-Wireless-Supports-10-9-10-14/dp/B07PB1X4CN) - Dual band alternative to WN725N.
[TP-Link Nano Router](http://www.amazon.com/TP-LINK-TL-WR702N-Wireless-Repeater-150Mpbs/dp/B007PTCFFW) - Though this isn't strictly a WiFi adapter, it does enable you to connect to WiFi network using the ethernet port of the Pi and is known to work correctly with Balena. As a result no further configuration is required.
```

That list does not come from meta-balena. We should add those devices to the rack, to the meta-balena README and then to the documentation. Otherwise move this information to a pattern instead, not to the documentation as `have been known to work` is not really useful.

Also, there is also a list of tested modem in `pages/reference/OS/network.md`. It also fetches from meta-balena but I am wondering if we should have just one place in the documentation to list these and then cross reference that, instead of sourcing twice from meta-balena.

**Comment by vipulgupta2048** [comment]
You got it, I agree on everything. I will add all of them in one place and will only have verified ones in the list.

**Comment by vipulgupta2048** [comment]
@alexgg Took a decision and pulled that entire section out from `network.md`, let me know how you feel about this now? Much clearer imho

**Comment by alexgg** [comment]
> @alexgg Took a decision and pulled that entire section out from `network.md`, let me know how you feel about this now? Much clearer imho

I agree. I wouldn't mind a link though but I don't have a strong opinion.

**Comment by vipulgupta2048** [comment]
@alexgg The link back to the page was added so all good. I will get this merged.

**Comment by vipulgupta2048** [comment]
@balena-ci I self-certify!

**Pull request merged**
