### PR TITLE
Update the add device modal screenshots

### PR DESCRIPTION
**Pull request by thgreasi**
Change-type: minor
See: https://github.com/balena-io/balena-ui/issues/4710
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Review by vipulgupta2048 — APPROVED** [review]
LGTM, @thgreasi you sure these are only screenshots for this modal that needs an update? If you can check that would be awesome, we can remove old screenshots and replace them with new ones.

**Comment by thgreasi** [comment]
No @vipulgupta2048 there are a few really outdated cases of that button showing in some of the device guides.
I'm planning to fix those in a second pass. Making those images is not fun :(

**Comment by thgreasi** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
> I'm planning to fix those in a second pass. Making those images is not fun :(

Welcome to a documentarian's world ❤️

**Pull request merged**
