### PR TITLE
Remove outdated section about systemd

### PR DESCRIPTION
**Pull request by markspanbroek**
Systemd is no longer supported in the base images, see: https://www.balena.io/docs/reference/base-images/base-images/#major-changes

### CODE REVIEW

**Comment by garethtdavies** [comment]
Thanks for the contribution @markspanbroek 

@shaunmulligan, while this section is clearly outdated, do we want to keep any of it with a note it is only applicable to certain versions? Even if we keep some of it this likely isn't the best place for it and suggest moving from here.

**Comment by shaunmulligan** [comment]
@garethtdavies yeah it might be good to keep this stuff around. We could just mention that this functionality is only supported on the discontinued `resin/` set of base images

**Comment by garethtdavies** [comment]
There is also this for the legacy resin images https://www.balena.io/docs/reference/base-images/legacy-base-images/#init-system so I'm in favor of simply stripping this to avoid confusion.

**Comment by garethtdavies** [comment]
@balena-ci retest

**Comment by garethtdavies** [comment]
@balena-ci retest

**Pull request merged**
