### PR TITLE
Document how to enable core dumps for containers

### PR DESCRIPTION
**Pull request by lmbarros**
This documents the change made in https://github.com/balena-os/meta-balena/pull/2849 .

### CODE REVIEW

**Comment by lmbarros** [comment]
Hey @vipulgupta2048 , can you take at look at this PR? Thanks!

**Review by vipulgupta2048 — COMMENTED** [review]
@lmbarros I might add a line or three about what core dumps are to provide context since you are adding this in a place where we are teaching people about multi-container setups and it might be a touch too niche for them. 

Otherwise, LGTM

**Comment by lmbarros** [comment]
Thanks @vipulgupta2048 , that's a great point! I updated the PR!

**Review by vipulgupta2048 — APPROVED** [review]
Thanks @lmbarros for the changes, ship it

**Pull request merged**
