### PR TITLE
deltas: fix links on deltas page

### PR DESCRIPTION
**Pull request by tmigone**
Closes: #1542
Change-type: patch
Signed-off-by: Tomás Migone <tomas@balena.io>

### CODE REVIEW

**Comment by tmigone** [comment]
@balena-ci rebase

**Comment by tmigone** [comment]
@balena-ci rebase

**Comment by tmigone** [comment]
@balena-ci rebase

**Review by pdcastro — APPROVED** [review]

**Comment by tmigone** [comment]
@balena-ci rebase

**Comment by tmigone** [comment]
@balena-ci retest

**Comment by tmigone** [comment]
@balena-ci rebase

**Comment by tmigone** [comment]
@balena-ci I self-certify!

**Comment by tmigone** [comment]
@balena-ci rebase

**Comment by tmigone** [comment]
@balena-ci rebase

**Pull request merged**
