### PR TITLE
Update more resources section to generate content dynamically

### PR DESCRIPTION
**Pull request by garethtdavies**
A WIP as likely we want to do this on a few more pages and finding a more flexible approach. Probably better to generate these pages via the build step vs. pulling directly from the GitHub API.

CleanShot 2020-04-28 at 13 26 56@2x

Change-type: minor
Signed-off-by: Gareth Davies <gareth@balena.io>

### CODE REVIEW

**Comment by garethtdavies** [comment]
Looking for a more flexible approach and into making this a partial using jq using the `fetch-external.sh` script:

```
curl https://api.github.com/orgs/balenalabs/repos | jq -r '.stargazers_count > 5 | sort_by(-.stargazers_count) | ["Name","Description","Link"], ["---","---","---"], (.[] | [.name,.description,.html_url]) | join ("|")' > balena-labs-projects.md
```

**Comment by xginn8** [comment]
@garethtdavies how about:

```shell
curl https://api.github.com/orgs/balenalabs/repos | jq -r 'sort_by(-.stargazers_count) |  (.[] | [.name,.html_url,.description] | "[\(.[0])]\(.[1])|\(.[2])") '
```

**Comment by garethtdavies** [comment]
Thank you! That works perfectly. I did add the `null` fix in too but agreed those should also be added to the repo. Lots of potential ways to add that header - I'm sure what I've pushed could be improved :)

In general @xginn8 how do you feel about the maintainability of this approach? I'm thinking we can use it for the balena-examples repos too to replace the manual seed projects page.

**Comment by xginn8** [comment]
> Thank you! That works perfectly. I did add the `null` fix in too but agreed those should also be added to the repo. Lots of potential ways to add that header - I'm sure what I've pushed could be improved :)
> 
> In general @xginn8 how do you feel about the maintainability of this approach? I'm thinking we can use it for the balena-examples repos too to replace the manual seed projects page.

I think this is _much better_ than maintaining those lists manually, but I do wonder if there's some sort of generalized solution for sourcing docs from upstream. I love me some `jq` but a heavier-duty language might make this cleaner.

**Comment by garethtdavies** [comment]
Updated this branch to get the "more resources" section to a better baseline as most of the content was grossly outdated and referencing things from 2015/2016. 

As noted above there are alternate ways of implementing this that might be more desirable particularly longer term. This is staged here https://resin-docs-preview.herokuapp.com/docs/learn/welcome/introduction/

**Comment by garethtdavies** [comment]
@balena-ci retest

**Comment by garethtdavies** [comment]
This fails to build jq on `ResinCI/npm/linux-alpine-x86_64-node10`:

```
Building jq from https://github.com/stedolan/jq/releases/download//jq-1.6/jq-1.6.tar.gz
{ Error: Command failed: /bin/sh -c autoreconf -fi
/bin/sh: autoreconf: not found
```

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by vipulgupta2048** [comment]
@pdcastro  @xginn8 This could be something I can work on next? Seems low-hanging enough, PR is about ready, just a few final touches and cleanup needed.

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
Closing. Continued in #1426

**Pull request closed without merging**
