### PR TITLE
device: Add Jetson Nano eMMC provisioning instructions

### PR DESCRIPTION
**Pull request by acostach**
Raising this PR in order to fix the missing jetson-nano-emmc page until the process gets fully automated. I'm not sure if this is the right format for the instructions, in order for them to appear when following this link: https://docs.balena.io/jetson-nano-emmc/nodejs/getting-started/#adding-your-first-device . If it's not, we can close this PR.

Addresses https://github.com/balena-io/docs/issues/1629

### CODE REVIEW

**Review by vipulgupta2048 — COMMENTED** [review]
@acostach I have deployed the branch on a preview build for you to check the Getting Started and see if the changes you made indeed is what you wanted. If it is feel free to merge it. 
https://resin-docs-preview.herokuapp.com/docs/learn/getting-started/jetson-nano-emmc/nodejs/

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
Thanks a lot @vipulgupta2048 , it looks fine but there's this link location for an image https://resin-docs-preview.herokuapp.com/docs/img/getting-started/create-application/jetson-nano-emmc.png which doesn't show up. Not sure what it should display and/or where it should be placed. Could it be that I need to create an image similar to this one and add it to my PR? https://github.com/balena-io/docs/blob/master/static/img/jetson-nano/app-type.png

**Comment by vipulgupta2048** [comment]
@acostach If you look at the preview, you actually need to take 3 custom screenshots of the dashboard as well.  
1. Create application - https://resin-docs-preview.herokuapp.com/docs/img/getting-started/create-application/raspberrypi3.png
2. Add device - https://resin-docs-preview.herokuapp.com/docs/img/getting-started/application/raspberrypi3.png
3. Create device - https://resin-docs-preview.herokuapp.com/docs/img/getting-started/devices/raspberrypi3.png

The screenshots need to be clicked exactly the way they are as the examples above then uploaded to the device-specific directory with the right names. Check this for reference - https://github.com/balena-io/docs/pull/1182

**Comment by acostach** [comment]
Thanks a lot for the detailed explanation @vipulgupta2048 , I pushed a second commit to add the images you mentioned

**Comment by vipulgupta2048** [comment]
Deploying again for sanity reasons. We really need to fix this process, hopefully the work I have started with contracts + getting started makes this super easy and not this much of going back and forth.

**Comment by vipulgupta2048** [comment]
@acostach It's deployed here
The only nitpick I would like you to fix is if you can anonymize the screenshot to hide your username/org_name (When creating an app). I am also working on getting a dummy org to help out with screenshots, things are in pipeline.

**Comment by acostach** [comment]
Thank you @vipulgupta2048 , I've updated the images to remove the org name as suggested. The test deploy still doesn't seem to display the screenshots although I used the names and paths according to the example, but I suspect that's only available for the test deploy.

**Comment by vipulgupta2048** [comment]
@acostach Definitely very weird as to why this is happening but not dismissing it. I will check it out for myself. 
Till then can you also fix Getting Started for [Nvidia Jetson Xavier NX Devkit SD-CARD](https://www.balena.io/docs/learn/getting-started/jetson-xavier-nx-devkit/nodejs/), it's the only other board missing its logo and other details. Since you have the context on how screenshots should be like, it will be easier for you to add. I think there is also an issue for this #1304

**Comment by acostach** [comment]
Sure @vipulgupta2048 , I added them in #1854

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
We did it @acostach Check out the deployment above for verification and ship this PR when you had a look https://resin-docs-preview.herokuapp.com/docs/learn/getting-started/jetson-xavier-nx-devkit/nodejs/

I will add you to one last issue where your context would be quite helpful.

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Pull request merged**
