### PR TITLE
Fixed broken Dev vs Prod broken links

### LINKED ISSUE #1819: Link to Development vs. Production images section of BalenaOS page is incorrect
I noticed that the Getting Started page includes a Note in the "Add your first device" section with a semi-broken link. The link is on the word "here" in the sentence "More details on the differences between Development and Production images are detailed here." The link is:

https://www.balena.io/docs/understanding/understanding-devices/2.0.0/#dev-vs-prod-images

The fragment identifying the section on the Host OS Overview page should be "#development-vs-production-images".

I see a lot of references to this page/section from the Getting Started page for the various devices and development languages. So, I'm guessing these pages are generated, and there must be some automated way to fix this issue. Maybe it makes more sense to just change the id of that header tag on the Overview page.

### PR DESCRIPTION
**Pull request by szony**
added correct anchor link in docs pointing at https://www.balena.io/docs/reference/OS/overview/2.x/#development-vs-production-images

### CODE REVIEW

**Comment by szony** [comment]
@balena-ci I self-certify!

**Review by szony — COMMENTED** [review]
Change-type: patch

**Review by vipulgupta2048 — CHANGES_REQUESTED** [review]
blocking merge

**Review by vipulgupta2048 — APPROVED** [review]
My bad, I apparently rebased a bit more than I should have to the point that git thinks I am making changes to versionbot's commits.

**Comment by kb2ma** [comment]
Works for me, too. Thanks!

**Pull request merged**
