### PR TITLE
jetson-xavier-nx-devkit: Add PNG images for this device type

### PR DESCRIPTION
**Pull request by acostach**
Images are the only part that is missing for this
device type, let's add them.

Change-type: patch
Signed-off-by: Alexandru Costache <alexandru@balena.io>

Connects to:
- https://github.com/balena-io/docs/issues/1624
- https://github.com/balena-io/docs/pull/1825#issuecomment-822486220

### CODE REVIEW

**Review by vipulgupta2048 — COMMENTED** [review]
@acostach Thanks for taking the time to fix this. Do we really need another Nvidia logo? Can't we use the same one each time around for all Nvidia devices if they have any visible change. Just checking. Otherwise, I have made the deployment again and rightly so we can't see the images still. Let's go ahead, merge this and see if the images show up right. I will create a issue to track the staging issue of images not showing.

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@vipulgupta2048 this logo has Xavier on it, the other has Nano..

**Comment by vipulgupta2048** [comment]
🤦🏼 Couldn't see it because of dark mode ...

**Review by vipulgupta2048 — APPROVED** [review]

**Pull request merged**
