### PR TITLE
Changed PR to Pull  Request

### PR DESCRIPTION
**Pull request by laurentava**
Changed PR to Pull  Request in first sentence.

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Thanks for opening the PR, you have missed the commit prefix to signify the change-type for your PR. Please read https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md#creating-commits-in-line-with-semantic-versioning

**Comment by laurentava** [comment]
@vipulgupta2048 so all I need to do is put patch: before my change correct? That's what I understand after reading the directions. Wanted to check with you.

**Comment by vipulgupta2048** [comment]
Yes, that's correct.  @laurentava when you are making the commit and writing the commit message, add the change-type prefix. In this PR, it will be patch.

**Comment by vipulgupta2048** [comment]
Hey @laurentava did you get a chance to look at this?

**Comment by laurentava** [comment]
> Hey @laurentava did you get a chance to look at this?

@vipulgupta2048 yes, I thought I fixed it. May need some tips on what to do to close out. Thanks!

**Comment by vipulgupta2048** [comment]
Happy to help @laurentava when you create a commit from the GitHub UI or from the terminal, you would need to add a prefix to your commit to signify what the change is. You can refer to this document about the same https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md#creating-commits-in-line-with-semantic-versioning and you actually did do it correctly in your first PR here https://github.com/balena-io/docs/pull/1866

Since, GitHub UI doesn't allow for editing the commits at this time. You can try again by opening a new pull request and make sure you add the commit prefix? It's all good.

**Comment by lurch** [comment]
I think there's a bit of confusion between "commit contents", and "commit comment"? And I'm not sure if the CONTRIBUTING.md makes that very clear either? I think for the automatic-versioning that Balena uses, the `patch: ` needs to be at the start of the commit comment? ("commit comment" might sometimes also be called "commit message")
"Commit contents" is the actual change, and "commit comment" is a description of the change.

In **this** PR, the commit contents are "Pull Request" and the commit comment is "Changed PR to Pull Request".

Whereas in #1866 the commit contents are "patch: pull request (PR)" and the commit comment is "Updated PR to pull request (PR)". Whereas I think what you _actually_ wanted was a commit content of "pull request (PR)" and a commit comment of "patch: Updated PR to pull request (PR)" ? :shrug:

**Comment by laurentava** [comment]
> I think there's a bit of confusion between "commit contents", and "commit comment"? And I'm not sure if the CONTRIBUTING.md makes that very clear either? I think for the automatic-versioning that Balena uses, the `patch: ` needs to be at the start of the commit comment? ("commit comment" might sometimes also be called "commit message")
> "Commit contents" is the actual change, and "commit comment" is a description of the change.
> 
> In **this** PR, the commit contents are "Pull Request" and the commit comment is "Changed PR to Pull Request".
> 
> Whereas in #1866 the commit contents are "patch: pull request (PR)" and the commit comment is "Updated PR to pull request (PR)". Whereas I think what you _actually_ wanted was a commit content of "pull request (PR)" and a commit comment of "patch: Updated PR to pull request (PR)" ? 🤷

Can you remind me where I go to create a new edit and request? And to confirm I will make the edit just like this: pull request (PR) in the actual doc. And then where do I put patch: Updated PR to pull request (PR)? 
Thanks for all your help!

**Pull request closed without merging**
