### PR TITLE
Update a number of broken links

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Relates to #1621

Extracted from https://github.com/balena-io/docs/pull/1658

### CODE REVIEW

**Review by pdcastro — APPROVED** [review]
Nice!

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@LucianBuzzo this has conflicts that need resolving

**Review by vipulgupta2048 — COMMENTED** [review]
Fixed the conflicts for my main man, @LucianBuzzo, and also rebased. 
Ready for takeoff 🚀

**Review by vipulgupta2048 — CHANGES_REQUESTED** [review]
Missed something, blocking the auto merge

**Review by vipulgupta2048 — APPROVED** [review]
Phew close one ✔️ 
Missed a conflict

**Pull request merged**
