### PR TITLE
Update screenshots for filter and tags

### PR DESCRIPTION
**Pull request by catt-tung**
Files for the screenshots updated to reflect current (April 2021) UI

### CODE REVIEW

**Review by vipulgupta2048 — COMMENTED** [review]
@catt-tung thanks for opening the PR, you seem to have missed the commit prefix to signify the change-type for your PR. Please read https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md#creating-commits-in-line-with-semantic-versioning

**Comment by catt-tung** [comment]
@balena-ci rebase

**Review by vipulgupta2048 — COMMENTED** [review]
All the screenshots look great @catt-tung except this one `static/img/common/app/add_tag_column.png`. It seems you might have cropped the the dropdown arrow. Was that intended?

Screenshot from 2021-04-16 18-01-03

Otherwise LGTM

**Comment by catt-tung** [comment]
@vipulgupta2048 yeah it's actually a very, very long list and it's not an internal scrollbar if that makes sense, so it didn't really fit in a screenshot unless I were to zoom out by a lot, but that would make it pixellated as well.

**Comment by nazrhom** [comment]
@balena-ci rebase

**Review by vipulgupta2048 — APPROVED** [review]

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Pull request merged**
