### PR TITLE
Removed typo

### LINKED ISSUE #1692: Intro page has a typo
https://www.balena.io/docs/learn/welcome/introduction/

In the "deploy" section it says "...your application from one to device to a fleet..."

### PR DESCRIPTION
**Pull request by poshrolls**
component: removed typo

Fixes #1692 

Change-type: patch
Signed-off-by: Laura Alison <laura@poshrolls.co.uk>

### CODE REVIEW

**Comment by 20k-ultra** [comment]
My diff is showing the only thing changed was a space added at the end of the paragraph.

**Comment by 20k-ultra** [comment]
duplicate of https://github.com/balena-io/docs/pull/1694 ?

**Review by poshrolls — COMMENTED** [review]
removed 'to'

**Review by 20k-ultra — APPROVED** [review]
nice find!

**Comment by 20k-ultra** [comment]
@balena-ci rebase

**Pull request merged**
