### PR TITLE
Changed OpenID Connect URL reference

### PR DESCRIPTION
**Pull request by ketilmo**
Updated URL from http to https
Change-type: patch

### CODE REVIEW

**Comment by xginn8** [comment]
thanks for the contribution @ketilmo! can you just add a footer to your commit with the following for the CI to pass:

```
Change-type: patch
```

If you can rebase & amend the commit to add that and push it back up, the tests should succeed (more info in CONTRIBUTING.md, here; https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md). Otherwise, looks great!

**Comment by ketilmo** [comment]
Change-type: patch

**Comment by ketilmo** [comment]
Will do, thanks!

**Comment by ketilmo** [comment]
@balena-ci retest

**Comment by ketilmo** [comment]
Messed up a bit here, will retry...

**Pull request closed without merging**
