### PR TITLE
Fix api docs to rename device to point to the right field

### PR DESCRIPTION
**Pull request by ZubairLK**
Fixes https://github.com/resin-io/docs/issues/898

### CODE REVIEW

**Comment by ZubairLK** [comment]
@Page- can you check the docs (https://docs.resin.io/reference/api/resources/device/) to rename a device. I think there is a mistake in them as the customer pointed out in https://app.frontapp.com/open/cnv_1089fab

I've made a PR with this commit via github.
But I'm not 100% sure if this is the right place for this update..

**Comment by Page-** [comment]
@ZubairLK `device_name` is correct but only for v4, older versions do use name, cc @CameronDiver was this change intentional as part of mc?

**Comment by CameronDiver** [comment]
@ZubairLK @Page- IIRC it was to do with env var changes, and `device has name` was colliding with one the new env vars.

**Comment by chrisys** [comment]
Closed in favour of #868

**Pull request closed without merging**
