### PR TITLE
Updating font, color, and navbar styles

### PR DESCRIPTION
**Pull request by nucleardreamer**
Change-type: patch
Signed-off-by: Flynn Joffray <flynn@balena.io>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by nucleardreamer** [comment]
@balena-ci retest

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by nucleardreamer** [comment]
@balena-ci rebase

**Comment by nucleardreamer** [comment]
@balena-ci I self-certify!

**Pull request merged**
