### PR TITLE
Enable dependabot for docker

### PR DESCRIPTION
**Pull request by thgreasi**
Change-type: patch

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by 20k-ultra** [comment]
From my understanding, dependabot will try to update https://github.com/balena-io/docs/blob/6d10aa3f910dc7cf2b55c3ecfc0e57fceadb7c05/Dockerfile#L1

Do you know if it only updates patch so we'll see PRs to `FROM node:14.0.5` for example ? Since we don't have a minor and patch version I'm worried if it will try to update major version.

**Comment by thgreasi** [comment]
@20k-ultra my intention is actually to get https://github.com/balena-io/docs/pull/1955 in before this one, so that it works as you describe.
Explained that to @vipulgupta2048 in a meet, but obviously I should have noted it in the description as well.

**Comment by 20k-ultra** [comment]
@balena-ci rebase

**Review by 20k-ultra — APPROVED** [review]

**Comment by thgreasi** [comment]
@balena-ci rebase

**Pull request merged**
