### PR TITLE
Add information about older devices and resin.io providing a 301 redi…

### PR DESCRIPTION
**Pull request by danthegoodman1**
Add information about older devices and resin.io providing a 301 redirect to balena-cloud.com

See https://github.com/balena-io/docs/issues/1401

### CODE REVIEW

**Comment by danthegoodman1** [comment]
@balena-ci rebase

**Comment by danthegoodman1** [comment]
@balena-ci rebase

**Comment by danthegoodman1** [comment]
@balena-ci rebase

**Comment by danthegoodman1** [comment]
@balena-ci rebase

**Review by vipulgupta2048 — APPROVED** [review]

**Comment by danthegoodman1** [comment]
@balena-ci rebase

**Pull request merged**
