### PR TITLE
Update the specification of balena.yml used for DWB

### PR DESCRIPTION
**Pull request by sradevski**
Depends-on: https://github.com/balena-io/balenahub/pull/56
Depends-on: https://github.com/balena-io/balenahub/pull/55
Depends-on: https://github.com/balena-io/balena-ui/pull/4528
Depends-on: https://github.com/balena-io/balena-builder/pull/839

Once all the dependent PRs are merged and deployed to production, we can go ahead and update all `balena.yml` files that exist out there to this new, updated schema
Change-type: minor
Signed-off-by: Stevche Radevski <stevche@balena.io>

### CODE REVIEW

**Comment by xginn8** [comment]
change lgtm, can self-certify whenever you're ready

**Review by phil-d-wilson — DISMISSED** [review]
lgtm

**Comment by sradevski** [comment]
@balena-ci rebase

**Comment by sradevski** [comment]
@balena-ci I self-certify!

**Pull request merged**
