### PR TITLE
patch: added .github/workflows/flowzone.yml

### PR DESCRIPTION
**Pull request by zoobot**
Signed-off-by: zoobot <rommims@gmail.com>

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
Can you delete the `.resinci.yml` as well please as it's redundant with flowzone

**Comment by Page-** [comment]
@vipulgupta2048 @zoobot if you want to retest with flowzone you use the button in the gh checks:
image

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Review by vipulgupta2048 — APPROVED** [review]
Really appreciate the help on this one folks!

**Pull request merged**
