### PR TITLE
Add information about environment variables in local development

### PR DESCRIPTION
**Pull request by benoit74**
Just a small suggestion to add:
- an example of resin-sync.yml modifications for local environment variables
- an information stating that you need to force the build of the container again for modifications to be applied
I spent quite a lot of time to figure all this out, so I believe it could be good to share.

### CODE REVIEW

**Comment by shaunmulligan** [comment]
Need to get resinCI to work on this

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by chrisys** [comment]
This is now redundant as both balena sync and balena local push have been deprecated.

**Pull request closed without merging**
