### PR TITLE
Add getting started for NanoPi Neo Air fixes #1647

### LINKED ISSUE #1647: Getting started needed for NanoPI Nano Air
Currently the getting started link points to: https://docs.resin.io/nanopi-neo-air/nodejs/getting-started/#adding-your-first-device

### PR DESCRIPTION
**Pull request by chrisys**
Change-type: patch
Signed-off-by: Chris Crocker-White <chriscw@balena.io>

### CODE REVIEW

**Comment by chrisys** [comment]
@balena-ci I self-certify!

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Pull request merged**
