### PR TITLE
Added note that inactive devices count against starter application limit

### LINKED ISSUE #1460: Should clarify that inactive devices do count against your starter app type device limit
Discussed in Product call 2020-06-09
See: https://www.flowdock.com/app/rulemotion/r-product/threads/E3zOf1tY5dcIsvx-MfUsIItXHzm
See: https://github.com/balena-io/balena-ui/issues/3735 (original issue)

### PR DESCRIPTION
**Pull request by mehalter**
Resolves #1460

Change-type: patch
Signed-off-by: Micah Halter <micah@balena.io>

### CODE REVIEW

**Comment by mehalter** [comment]
@balena-ci I self-certify!

**Comment by mehalter** [comment]
@balena-ci rebase

**Comment by mehalter** [comment]
@balena-ci rebase

**Comment by mehalter** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by mehalter** [comment]
@balena-ci rebase

**Pull request merged**
