### PR TITLE
Change use of "resin" to "balena" in README

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Change-type: patch
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

### CODE REVIEW

**Review by xginn8 — APPROVED** [review]

**Comment by xginn8** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by Page-** [comment]
@balena-ci rebase

**Comment by LucianBuzzo** [comment]
@balena-ci rebase

**Pull request merged**
